version: "3.7"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - levensta
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - levensta
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - levensta
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/wp

networks:
  levensta:
    driver: bridge