version: "3.3"

services:
  nginx:
    container_name: nginx
    restart: always
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - levensta-network
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    restart: always
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - levensta-network
    env_file:
      - ./.env
    tty: true

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - levensta-network
    env_file:
      - ./.env
    tty: true

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
  levensta-network:
    driver: bridge